//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public int idProduto { get; set; }
        public string nome { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<bool> disponivel { get; set; }
        public int Cliente_idCliente { get; set; }
    
        public virtual cliente cliente { get; set; }
    }
}
